### ISSUE TITLE
✨연말정산 결과 DB 설계 및 API 

### ISSUE THREAD

**Issue by youhyeoneee** [13th-month-lucky/backend#17]
## 📌 Description
- 연말정산 미리보기 결과를 저장할 DB와 API가 필요합니다.

## 📝 To-do
- [x] Results 스키마 : userId(object id), data (json), created (time)
- [x] user의 모든 연말정산 결과 조회하기
- [x]  user의 연말정산 결과 생성
- [x] 결과 ID로 조회하기
